// Generates a formatted, printable VPAT-style HTML document from wizard
// state. Pure function: (state) -> HTML string. Escapes all user-supplied
// text (product info, remarks) — never inject raw user input into markup.

import { CRITERIA, PRINCIPLES, CONFORMANCE_LEVELS } from './criteria.js';

export function escapeHTML(str) {
    if (str == null) return '';
    return String(str)
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;');
}

const LEVEL_LABEL = Object.fromEntries(CONFORMANCE_LEVELS.map(l => [l.id, l.label]));

function renderCriterionRow(criterion, entry) {
    const level = entry?.level || 'not-evaluated';
    const remarks = entry?.remarks || '';
    return `
        <tr>
            <td class="crit-id">${escapeHTML(criterion.id)}</td>
            <td class="crit-title">${escapeHTML(criterion.title)}<span class="crit-level-badge">Level ${escapeHTML(criterion.level)}</span></td>
            <td class="crit-conformance">${escapeHTML(LEVEL_LABEL[level] || 'Not Evaluated')}</td>
            <td class="crit-remarks">${remarks ? escapeHTML(remarks) : '<span class="empty">—</span>'}</td>
        </tr>
    `;
}

function renderPrincipleSection(principle) {
    const rows = CRITERIA
        .filter(c => c.principle === principle.id)
        .map(c => ({ criterion: c }));
    return { principle, rows };
}

export function generateReportHTML(state, { watermark = false } = {}) {
    const { productInfo, entries } = state;
    const generatedDate = new Date(state._generatedAt || Date.now()).toISOString().slice(0, 10);

    const sections = PRINCIPLES.map(p => {
        const criteriaForPrinciple = CRITERIA.filter(c => c.principle === p.id);
        const rowsHTML = criteriaForPrinciple.map(c => renderCriterionRow(c, entries[c.id])).join('');
        return `
            <h2>${escapeHTML(p.label)}</h2>
            <table class="vpat-table">
                <thead>
                    <tr><th>Criteria</th><th>Description</th><th>Conformance Level</th><th>Remarks and Explanations</th></tr>
                </thead>
                <tbody>${rowsHTML}</tbody>
            </table>
        `;
    }).join('');

    const summaryCounts = CONFORMANCE_LEVELS.map(l => ({
        label: l.label,
        count: CRITERIA.filter(c => (entries[c.id]?.level || 'not-evaluated') === l.id).length
    }));

    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>VPAT / Accessibility Conformance Report — ${escapeHTML(productInfo.productName || 'Untitled Product')}</title>
<style>
  body { font-family: Georgia, 'Times New Roman', serif; max-width: 900px; margin: 40px auto; padding: 0 20px; color: #1a1a1a; line-height: 1.5; }
  h1 { font-size: 1.6rem; border-bottom: 3px solid #1a1a1a; padding-bottom: 10px; }
  h2 { font-size: 1.2rem; margin-top: 36px; }
  .meta-table { width: 100%; border-collapse: collapse; margin: 20px 0; }
  .meta-table td { padding: 6px 10px; border: 1px solid #ccc; vertical-align: top; }
  .meta-table td:first-child { font-weight: bold; width: 220px; background: #f5f5f5; }
  .vpat-table { width: 100%; border-collapse: collapse; margin-bottom: 24px; font-size: 0.92rem; }
  .vpat-table th, .vpat-table td { border: 1px solid #ccc; padding: 8px 10px; text-align: left; vertical-align: top; }
  .vpat-table th { background: #2b2620; color: white; }
  .crit-id { white-space: nowrap; font-weight: bold; width: 60px; }
  .crit-level-badge { display: inline-block; margin-left: 8px; font-size: 0.75rem; color: #666; font-weight: normal; }
  .empty { color: #999; }
  .disclaimer { background: #fff8e1; border: 1px solid #e0c34a; padding: 14px 18px; border-radius: 6px; margin: 24px 0; font-size: 0.9rem; }
  .summary-grid { display: flex; gap: 14px; flex-wrap: wrap; margin: 16px 0; }
  .summary-chip { background: #f0f0f0; border-radius: 6px; padding: 8px 14px; font-size: 0.85rem; }
  ${watermark ? '.watermark { position: fixed; top: 40%; left: 10%; font-size: 4rem; color: rgba(200,60,60,0.15); transform: rotate(-25deg); pointer-events: none; z-index: 999; }' : ''}
  @media print { body { margin: 0; } }
</style>
</head>
<body>
${watermark ? '<div class="watermark">PREVIEW — NOT FOR DISTRIBUTION</div>' : ''}
<h1>Voluntary Product Accessibility Template (VPAT®) — Draft</h1>
<p class="disclaimer">
  <strong>This is an accessibility conformance report DRAFT generated by VPAT Draft, a drafting
  accelerator.</strong> It reflects self-reported conformance levels entered by the evaluator above
  and has not been independently verified. It is not a certification, guarantee, or legal
  determination of accessibility conformance. Evaluate accuracy before distributing.
</p>

<table class="meta-table">
  <tr><td>Product Name</td><td>${escapeHTML(productInfo.productName) || '<span class="empty">—</span>'}</td></tr>
  <tr><td>Product Version</td><td>${escapeHTML(productInfo.productVersion) || '<span class="empty">—</span>'}</td></tr>
  <tr><td>Vendor Name</td><td>${escapeHTML(productInfo.vendorName) || '<span class="empty">—</span>'}</td></tr>
  <tr><td>Vendor Contact</td><td>${escapeHTML(productInfo.vendorContact) || '<span class="empty">—</span>'}</td></tr>
  <tr><td>Evaluation Date</td><td>${escapeHTML(productInfo.evaluationDate) || '<span class="empty">—</span>'}</td></tr>
  <tr><td>Evaluation Methods Used</td><td>${escapeHTML(productInfo.evaluationMethods) || '<span class="empty">—</span>'}</td></tr>
  <tr><td>Report Generated</td><td>${escapeHTML(generatedDate)}</td></tr>
  <tr><td>Standard</td><td>WCAG 2.2 Level A and AA</td></tr>
</table>

<div class="summary-grid">
${summaryCounts.map(s => `<span class="summary-chip">${escapeHTML(s.label)}: ${s.count}</span>`).join('')}
</div>

${sections}

</body>
</html>`;
}
